# ROS2 Parameter File for joy_msg_router - Default teleop configuration
# This file is converted from the old default.yaml configuration format
# Use with: ros2 run joy_msg_router_rs joy_msg_router --ros-args --params-file path/to/this/file.yaml

joy_msg_router:
  ros__parameters:
    # Profile name
    profile_name: "teleop"
    
    # No enable button for basic teleop profile
    # enable_button: 4  # Uncomment to require L1/LB button to be held
    
    # Input mappings
    
    # Mapping 0: Forward/backward movement (left stick Y-axis)
    input_mappings.0.source_type: "axis"
    input_mappings.0.source_index: 1
    input_mappings.0.action_type: "publish"
    input_mappings.0.topic: "/cmd_vel"
    input_mappings.0.message_type: "geometry_msgs/msg/Twist"
    input_mappings.0.field: "linear.x"
    input_mappings.0.scale: 0.5
    input_mappings.0.offset: 0.0
    input_mappings.0.deadzone: 0.1
    
    # Mapping 1: Rotation (right stick X-axis)
    input_mappings.1.source_type: "axis"
    input_mappings.1.source_index: 3
    input_mappings.1.action_type: "publish"
    input_mappings.1.topic: "/cmd_vel"
    input_mappings.1.message_type: "geometry_msgs/msg/Twist"
    input_mappings.1.field: "angular.z"
    input_mappings.1.scale: 1.0
    input_mappings.1.offset: 0.0
    input_mappings.1.deadzone: 0.1
    
    # Mapping 2: Emergency stop (X/Square button)
    input_mappings.2.source_type: "button"
    input_mappings.2.source_index: 0
    input_mappings.2.action_type: "publish"
    input_mappings.2.topic: "/cmd_vel"
    input_mappings.2.message_type: "geometry_msgs/msg/Twist"
    input_mappings.2.field: "linear.x"
    input_mappings.2.scale: 0.0  # Zero output for stop
    input_mappings.2.offset: 0.0
    input_mappings.2.deadzone: 0.0