# Joy Message Router Configuration
# This file defines profiles for routing joystick inputs to ROS messages
#
# Supported action types:
# - publish: Publish values to ROS topics
# - call_service: Call ROS services 
# - modifier: Dynamically modify other mappings' scale, offset, and deadzone
#
# Modifier targets can be specified by:
# - mapping_id: Target specific mappings by their ID
# - source: Target all mappings from a specific source (axis/button)

# Default profile to use when none is specified
default_profile: "teleop"

# Profile definitions
profiles:
  # Teleoperation profile for robot movement
  teleop:
    # Unified input mappings for both axes and buttons
    input_mappings:
      # Forward/backward movement (left stick Y-axis)
      - source_type: axis
        source_index: 1
        scale: 0.5              # Maximum output value (m/s for linear, rad/s for angular)
        offset: 0.0             # Offset added after scaling
        deadzone: 0.1           # Values below this threshold are treated as zero
        action:
          type: publish
          topic: "/cmd_vel"
          message_type: "geometry_msgs/msg/Twist"
          field: "linear.x"       # Options: linear_x, linear_y, linear_z, angular_x, angular_y, angular_z
      
      # Rotation (right stick X-axis)
      - source_type: axis
        source_index: 3
        scale: 1.0
        offset: 0.0
        deadzone: 0.1
        action:
          type: publish
          topic: "/cmd_vel"
          message_type: "geometry_msgs/msg/Twist"
          field: "angular.z"
    
      # X button - emergency stop (publishes zero twist)
      - source_type: button
        source_index: 0
        action:
          type: publish
          topic: "/cmd_vel"
          message_type: "geometry_msgs/msg/Twist"
          field: "linear.x"
        scale: 0.0    # Zero output for emergency stop
        offset: 0.0
        deadzone: 0.0

  # Safe teleoperation with deadman switch
  teleop_safe:
    # L1 button (4) must be held to enable movement
    enable_button: 4
    
    input_mappings:
      # Same as teleop but with reduced speeds
      - source_type: axis
        source_index: 1
        scale: 0.3        # Reduced max speed for safety
        offset: 0.0
        deadzone: 0.1
        action:
          type: publish
          topic: "/cmd_vel"
          message_type: "geometry_msgs/msg/Twist"
          field: "linear.x"
      
      - source_type: axis
        source_index: 3
        scale: 0.5        # Reduced rotation speed
        offset: 0.0
        deadzone: 0.1
        action:
          type: publish
          topic: "/cmd_vel"
          message_type: "geometry_msgs/msg/Twist"
          field: "angular.z"
    
      # Triangle button - call service to change mode
      - source_type: button
        source_index: 2
        action:
          type: call_service
          service_name: "/set_navigation_mode"
          service_type: "std_srvs/srv/SetBool"
      
      # Circle button - trigger a custom action
      - source_type: button
        source_index: 1
        action:
          type: call_service
          service_name: "/trigger_action"
          service_type: "std_srvs/srv/Trigger"

  # Profile with modifier support for dynamic control
  teleop_with_modifiers:
    input_mappings:
      # Forward/backward movement with ID for modifier targeting
      - id: "forward_movement"
        source_type: axis
        source_index: 1
        scale: 0.5
        offset: 0.0
        deadzone: 0.1
        action:
          type: publish
          topic: "/cmd_vel"
          message_type: "geometry_msgs/msg/Twist"
          field: "linear.x"
      
      # Rotation with ID for modifier targeting
      - id: "rotation"
        source_type: axis
        source_index: 3
        scale: 0.8
        offset: 0.0
        deadzone: 0.1
        action:
          type: publish
          topic: "/cmd_vel"
          message_type: "geometry_msgs/msg/Twist"
          field: "angular.z"
      
      # R1 button - Turbo mode (doubles speed)
      - source_type: button
        source_index: 5
        action:
          type: modifier
          targets:
            - mapping_id: "forward_movement"
            - mapping_id: "rotation"
          scale_multiplier: 2.0
      
      # L1 button - Precision mode (30% speed)
      - source_type: button
        source_index: 4
        action:
          type: modifier
          targets:
            - mapping_id: "forward_movement"
            - mapping_id: "rotation"
          scale_multiplier: 0.3
          deadzone_override: 0.05  # Reduce deadzone for fine control
      
      # Right trigger - Variable speed boost
      - source_type: axis
        source_index: 5
        scale: 1.0
        deadzone: 0.1
        action:
          type: modifier
          targets:
            - source:
                type: axis
                index: 1  # Modify left stick Y
          scale_multiplier: 3.0   # Up to 3x speed at full trigger
          apply_gradually: true   # Scale based on trigger position
      
      # X button - Emergency stop (zero all movement)
      - source_type: button
        source_index: 0
        action:
          type: modifier
          targets:
            - source:
                type: axis
                index: 1  # Left stick Y
            - source:
                type: axis
                index: 3  # Right stick X
          scale_multiplier: 0.0   # Zero out movement

  # Example profile with multiple output types
  multi_output:
    input_mappings:
      # Axis to twist field
      - source_type: axis
        source_index: 0
        scale: 1.0
        offset: 0.0
        deadzone: 0.05
        action:
          type: publish
          topic: "/cmd_vel"
          message_type: "geometry_msgs/msg/Twist"
          field: "linear.x"
      
      # Button to boolean message
      - source_type: button
        source_index: 5
        action:
          type: publish
          topic: "/lights/enable"
          message_type: "std_msgs/msg/Bool"
          once: true    # Publish only on button press, not continuously
      
      # Button to integer message
      - source_type: button
        source_index: 6
        action:
          type: publish
          topic: "/mode/select"
          message_type: "std_msgs/msg/Int32"
          once: true
      
      # Button to float message
      - source_type: button
        source_index: 7
        action:
          type: publish
          topic: "/speed/multiplier"
          message_type: "std_msgs/msg/Float64"
          once: false   # Publish continuously while pressed
      
      # Button to string message
      - source_type: button
        source_index: 8
        action:
          type: publish
          topic: "/status/message"
          message_type: "std_msgs/msg/String"
          once: true