# ROS2 Parameter File for joy_msg_router - Multi-output configuration
# This file is converted from the old default.yaml configuration format
# Use with: ros2 run joy_msg_router_rs joy_msg_router --ros-args --params-file path/to/this/file.yaml

joy_msg_router:
  ros__parameters:
    # Profile name
    profile_name: "multi_output"
    
    # Input mappings
    
    # Mapping 0: Axis to twist field
    input_mappings.0.source_type: "axis"
    input_mappings.0.source_index: 0
    input_mappings.0.action_type: "publish"
    input_mappings.0.topic: "/cmd_vel"
    input_mappings.0.message_type: "geometry_msgs/msg/Twist"
    input_mappings.0.field: "linear.x"
    input_mappings.0.scale: 1.0
    input_mappings.0.offset: 0.0
    input_mappings.0.deadzone: 0.05
    
    # Mapping 1: Button to boolean message
    input_mappings.1.source_type: "button"
    input_mappings.1.source_index: 5
    input_mappings.1.action_type: "publish"
    input_mappings.1.topic: "/lights/enable"
    input_mappings.1.message_type: "std_msgs/msg/Bool"
    input_mappings.1.once: true  # Publish only on button press, not continuously
    input_mappings.1.scale: 1.0
    
    # Mapping 2: Button to integer message
    input_mappings.2.source_type: "button"
    input_mappings.2.source_index: 6
    input_mappings.2.action_type: "publish"
    input_mappings.2.topic: "/mode/select"
    input_mappings.2.message_type: "std_msgs/msg/Int32"
    input_mappings.2.once: true
    input_mappings.2.scale: 1.0
    
    # Mapping 3: Button to float message
    input_mappings.3.source_type: "button"
    input_mappings.3.source_index: 7
    input_mappings.3.action_type: "publish"
    input_mappings.3.topic: "/speed/multiplier"
    input_mappings.3.message_type: "std_msgs/msg/Float64"
    input_mappings.3.once: false  # Publish continuously while pressed
    input_mappings.3.scale: 1.0
    
    # Mapping 4: Button to string message
    input_mappings.4.source_type: "button"
    input_mappings.4.source_index: 8
    input_mappings.4.action_type: "publish"
    input_mappings.4.topic: "/status/message"
    input_mappings.4.message_type: "std_msgs/msg/String"
    input_mappings.4.once: true
    input_mappings.4.scale: 1.0