default_profile: "sequences_demo"

profiles:
  sequences_demo:
    enable_button: 4  # Right shoulder button enables output
    
    # Define macros for reusable action sequences
    macros:
      dance_move:
        description: "Performs a simple dance move"
        parameters:
          speed:
            type: "number"
            default: 1.0
            description: "Movement speed multiplier"
          duration:
            type: "number" 
            default: 500
            description: "Duration in milliseconds"
        actions:
          - action:
              type: "publish_twist"
              linear_x: 0.0
              linear_y: 0.0
              linear_z: 0.0
              angular_x: 0.0
              angular_y: 0.0
              angular_z: 2.0
              once: true
            delay_ms: 0
            duration_ms: 250
          - action:
              type: "publish_twist"
              linear_x: 0.0
              linear_y: 0.0
              linear_z: 0.0
              angular_x: 0.0
              angular_y: 0.0
              angular_z: -2.0
              once: true
            delay_ms: 0
            duration_ms: 250
          - action:
              type: "no_action"
            delay_ms: 0
            duration_ms: 0
      
      emergency_stop:
        description: "Emergency stop sequence"
        parameters: {}
        actions:
          - action:
              type: "publish_bool"
              topic: "/emergency_stop"
              value: true
              once: true
            delay_ms: 0
            duration_ms: 0
          - action:
              type: "no_action"
            delay_ms: 100
            duration_ms: 0
          - action:
              type: "publish_bool"
              topic: "/emergency_stop"
              value: false
              once: true
            delay_ms: 0
            duration_ms: 0
    
    # Axis mappings for normal joystick control
    axis_mappings:
      - joy_axis: 1
        output_field: "linear_x"
        scale: 2.0
        offset: 0.0
        deadzone: 0.1
      - joy_axis: 0  
        output_field: "angular_z"
        scale: -1.0
        offset: 0.0
        deadzone: 0.1
    
    # Button mappings with sequences and macros
    button_mappings:
      # Triangle button - Execute dance macro
      - button: 0
        action:
          type: "execute_macro"
          macro_name: "dance_move"
          parameters:
            speed: 1.5
            duration: 750
          once: true
      
      # Circle button - Emergency stop macro
      - button: 1
        action:
          type: "execute_macro"
          macro_name: "emergency_stop"
          parameters: {}
          once: true
      
      # X button - Simple movement sequence
      - button: 2
        action:
          type: "action_sequence"
          once: true
          repeat: false
          actions:
            - action:
                type: "publish_twist"
                linear_x: 1.0
                linear_y: 0.0
                linear_z: 0.0
                angular_x: 0.0
                angular_y: 0.0
                angular_z: 0.0
                once: true
              delay_ms: 0
              duration_ms: 500
            - action:
                type: "publish_twist"
                linear_x: 0.0
                linear_y: 1.0
                linear_z: 0.0
                angular_x: 0.0
                angular_y: 0.0
                angular_z: 0.0
                once: true
              delay_ms: 100
              duration_ms: 500
            - action:
                type: "no_action"
              delay_ms: 100
              duration_ms: 0
      
      # Square button - Repeating sequence while held
      - button: 3
        action:
          type: "action_sequence"
          once: false
          repeat: true
          actions:
            - action:
                type: "publish_bool"
                topic: "/heartbeat"
                value: true
                once: true
              delay_ms: 0
              duration_ms: 100
            - action:
                type: "publish_bool"
                topic: "/heartbeat"
                value: false
                once: true
              delay_ms: 400
              duration_ms: 100
      
      # L1 button - Multi-step service sequence
      - button: 6
        action:
          type: "action_sequence"
          once: true
          repeat: false
          actions:
            - action:
                type: "call_service"
                service_name: "/robot/arm/prepare"
                service_type: "std_srvs/srv/Trigger"
                once: true
              delay_ms: 0
              duration_ms: 0
            - action:
                type: "publish_string"
                topic: "/robot/status"
                value: "Arm prepared"
                once: true
              delay_ms: 1000
              duration_ms: 0
            - action:
                type: "call_service"
                service_name: "/robot/arm/execute"
                service_type: "std_srvs/srv/Trigger"
                once: true
              delay_ms: 500
              duration_ms: 0
      
      # R1 button - Complex sequence with multiple message types
      - button: 7
        action:
          type: "action_sequence"
          once: true
          repeat: false
          actions:
            - action:
                type: "publish_int32"
                topic: "/sequence_counter"
                value: 1
                once: true
              delay_ms: 0
              duration_ms: 0
            - action:
                type: "publish_float64"
                topic: "/progress"
                value: 0.25
                once: true
              delay_ms: 250
              duration_ms: 0
            - action:
                type: "publish_float64"
                topic: "/progress"
                value: 0.50
                once: true
              delay_ms: 250
              duration_ms: 0
            - action:
                type: "publish_float64"
                topic: "/progress"
                value: 0.75
                once: true
              delay_ms: 250
              duration_ms: 0
            - action:
                type: "publish_float64"
                topic: "/progress"
                value: 1.0
                once: true
              delay_ms: 250
              duration_ms: 0
            - action:
                type: "publish_string"
                topic: "/status"
                value: "Sequence complete"
                once: true
              delay_ms: 100
              duration_ms: 0