default_profile: "advanced_control"

profiles:
  advanced_control:
    enable_button: 4  # Right shoulder button enables output
    
    # Define state machines for complex behaviors
    state_machines:
      weapon_system:
        name: "weapon_system"
        description: "Weapon system with safety interlocks"
        initial_state: "safe"
        states:
          safe:
            name: "safe"
            description: "Weapons are disabled and safe"
            on_enter:
              - type: "publish_bool"
                topic: "/weapon/armed"
                value: false
                once: true
              - type: "publish_string"
                topic: "/weapon/status"
                value: "SAFE - Weapons disabled"
                once: true
            transitions:
              - target_state: "arming"
                condition:
                  type: "button_combo"
                  buttons: [0, 1]  # Triangle + Circle
                  require_all: true
                priority: 1
          
          arming:
            name: "arming"
            description: "Waiting for arming confirmation"
            on_enter:
              - type: "publish_string"
                topic: "/weapon/status"
                value: "ARMING - Press X to confirm, Square to cancel"
                once: true
            transitions:
              - target_state: "armed"
                condition:
                  type: "button_press"
                  button: 2  # X button
                priority: 1
              - target_state: "safe"
                condition:
                  type: "button_press"
                  button: 3  # Square button
                priority: 2
            timeout_ms: 5000
            timeout_target: "safe"
          
          armed:
            name: "armed"
            description: "Weapons are armed and ready"
            on_enter:
              - type: "publish_bool"
                topic: "/weapon/armed"
                value: true
                once: true
              - type: "publish_string"
                topic: "/weapon/status"
                value: "ARMED - R1 to fire, Square to disarm"
                once: true
            on_exit:
              - type: "publish_string"
                topic: "/weapon/status"
                value: "Disarming..."
                once: true
            transitions:
              - target_state: "firing"
                condition:
                  type: "button_press"
                  button: 7  # R1 button
                priority: 1
              - target_state: "safe"
                condition:
                  type: "button_press"
                  button: 3  # Square button
                priority: 1
              - target_state: "safe"
                condition:
                  type: "button_sequence"
                  buttons: [5, 6, 7]  # L1, L2, R1 sequence
                  timeout_ms: 2000
                priority: 2
            timeout_ms: 10000
            timeout_target: "safe"
          
          firing:
            name: "firing"
            description: "Weapon is firing"
            on_enter:
              - type: "publish_bool"
                topic: "/weapon/fire"
                value: true
                once: true
              - type: "publish_string"
                topic: "/weapon/status"
                value: "FIRING!"
                once: true
            on_exit:
              - type: "publish_bool"
                topic: "/weapon/fire"
                value: false
                once: true
            transitions:
              - target_state: "armed"
                condition:
                  type: "always"
                delay_ms: 500
                priority: 1
      
      navigation_mode:
        name: "navigation_mode"
        description: "Navigation mode state machine"
        initial_state: "manual"
        states:
          manual:
            name: "manual"
            description: "Manual control mode"
            on_enter:
              - type: "publish_string"
                topic: "/nav/mode"
                value: "MANUAL"
                once: true
              - type: "publish_string"
                topic: "/nav/status"
                value: "Manual control active - Hold Select for 2s for autonomous"
                once: true
            transitions:
              - target_state: "autonomous"
                condition:
                  type: "button_held"
                  button: 8  # Select button
                  duration_ms: 2000
                priority: 1
          
          autonomous:
            name: "autonomous"
            description: "Autonomous navigation mode"
            on_enter:
              - type: "publish_string"
                topic: "/nav/mode"
                value: "AUTONOMOUS"
                once: true
              - type: "call_service"
                service_name: "/nav/start_autonomous"
                service_type: "std_srvs/srv/Trigger"
                once: true
              - type: "publish_string"
                topic: "/nav/status"
                value: "Autonomous navigation active - Press Start to return to manual"
                once: true
            on_exit:
              - type: "call_service"
                service_name: "/nav/stop_autonomous"
                service_type: "std_srvs/srv/Trigger"
                once: true
            transitions:
              - target_state: "manual"
                condition:
                  type: "button_press"
                  button: 9  # Start button
                priority: 1
      
      drone_flight_mode:
        name: "drone_flight_mode"
        description: "Drone flight mode with safety checks"
        initial_state: "grounded"
        states:
          grounded:
            name: "grounded"
            description: "Drone is on the ground"
            on_enter:
              - type: "publish_string"
                topic: "/drone/status"
                value: "GROUNDED - Press both sticks to arm"
                once: true
            transitions:
              - target_state: "armed"
                condition:
                  type: "button_combo"
                  buttons: [10, 11]  # Both stick presses
                  require_all: true
                priority: 1
          
          armed:
            name: "armed"
            description: "Drone is armed but not flying"
            on_enter:
              - type: "publish_string"
                topic: "/drone/status"
                value: "ARMED - Throttle up to take off"
                once: true
            transitions:
              - target_state: "flying"
                condition:
                  type: "custom"
                  condition_id: "throttle_up"
                priority: 1
              - target_state: "grounded"
                condition:
                  type: "button_press"
                  button: 3  # Square to disarm
                priority: 1
            timeout_ms: 30000  # Auto-disarm after 30 seconds
            timeout_target: "grounded"
          
          flying:
            name: "flying"
            description: "Drone is in flight"
            on_enter:
              - type: "publish_string"
                topic: "/drone/status"
                value: "FLYING - Throttle down to land"
                once: true
            on_update:
              - type: "publish_bool"
                topic: "/drone/heartbeat"
                value: true
                once: false
            transitions:
              - target_state: "landing"
                condition:
                  type: "custom"
                  condition_id: "throttle_down"
                priority: 1
              - target_state: "emergency"
                condition:
                  type: "button_press"
                  button: 3  # Emergency land
                priority: 2
          
          landing:
            name: "landing"
            description: "Drone is landing"
            on_enter:
              - type: "publish_string"
                topic: "/drone/status"
                value: "LANDING..."
                once: true
            transitions:
              - target_state: "grounded"
                condition:
                  type: "always"
                delay_ms: 3000  # 3 second landing sequence
                priority: 1
          
          emergency:
            name: "emergency"
            description: "Emergency landing mode"
            on_enter:
              - type: "publish_string"
                topic: "/drone/status"
                value: "EMERGENCY LANDING!"
                once: true
              - type: "call_service"
                service_name: "/drone/emergency_land"
                service_type: "std_srvs/srv/Trigger"
                once: true
            transitions:
              - target_state: "grounded"
                condition:
                  type: "always"
                delay_ms: 5000  # 5 second emergency landing
                priority: 1
    
    # Regular axis mappings still work alongside state machines
    axis_mappings:
      - joy_axis: 1
        output_field: "linear_x"
        scale: 2.0
        offset: 0.0
        deadzone: 0.1
      - joy_axis: 0
        output_field: "angular_z"
        scale: -1.0
        offset: 0.0
        deadzone: 0.1
    
    # Button mappings can control state machines
    button_mappings:
      # D-pad controls weapon system
      - button: 12  # D-pad up
        action:
          type: "state_machine_action"
          state_machine: "weapon_system"
          action:
            type: "start"
      
      - button: 13  # D-pad down
        action:
          type: "state_machine_action"
          state_machine: "weapon_system"
          action:
            type: "reset"
      
      # Left/Right arrows control navigation
      - button: 14  # D-pad left
        action:
          type: "state_machine_action"
          state_machine: "navigation_mode"
          action:
            type: "transition_to"
            state: "manual"
      
      - button: 15  # D-pad right
        action:
          type: "state_machine_action"
          state_machine: "navigation_mode"
          action:
            type: "transition_to"
            state: "autonomous"
      
      # Shoulder buttons control drone flight mode
      - button: 6  # L2
        action:
          type: "state_machine_action"
          state_machine: "drone_flight_mode"
          action:
            type: "start"