# ROS2 Parameter File for joy_msg_router - Safe teleop configuration
# This file is converted from the old default.yaml configuration format
# Use with: ros2 run joy_msg_router_rs joy_msg_router --ros-args --params-file path/to/this/file.yaml

joy_msg_router:
  ros__parameters:
    # Profile name
    profile_name: "teleop_safe"
    
    # L1 button (4) must be held to enable movement
    enable_button: 4
    
    # Input mappings
    
    # Mapping 0: Forward/backward movement (left stick Y-axis) - reduced speed for safety
    input_mappings.0.source_type: "axis"
    input_mappings.0.source_index: 1
    input_mappings.0.action_type: "publish"
    input_mappings.0.topic: "/cmd_vel"
    input_mappings.0.message_type: "geometry_msgs/msg/Twist"
    input_mappings.0.field: "linear.x"
    input_mappings.0.scale: 0.3  # Reduced max speed for safety
    input_mappings.0.offset: 0.0
    input_mappings.0.deadzone: 0.1
    
    # Mapping 1: Rotation (right stick X-axis) - reduced speed for safety
    input_mappings.1.source_type: "axis"
    input_mappings.1.source_index: 3
    input_mappings.1.action_type: "publish"
    input_mappings.1.topic: "/cmd_vel"
    input_mappings.1.message_type: "geometry_msgs/msg/Twist"
    input_mappings.1.field: "angular.z"
    input_mappings.1.scale: 0.5  # Reduced rotation speed
    input_mappings.1.offset: 0.0
    input_mappings.1.deadzone: 0.1
    
    # Mapping 2: Triangle button - call service to change mode
    input_mappings.2.source_type: "button"
    input_mappings.2.source_index: 2
    input_mappings.2.action_type: "call_service"
    input_mappings.2.service_name: "/set_navigation_mode"
    input_mappings.2.service_type: "std_srvs/srv/SetBool"
    
    # Mapping 3: Circle button - trigger a custom action
    input_mappings.3.source_type: "button"
    input_mappings.3.source_index: 1
    input_mappings.3.action_type: "call_service"
    input_mappings.3.service_name: "/trigger_action"
    input_mappings.3.service_type: "std_srvs/srv/Trigger"