# Example configuration demonstrating modifier functionality
# This shows how buttons and axes can modify the behavior of other mappings

default_profile: "turbo_precision"

profiles:
  # Profile with turbo and precision modifiers
  turbo_precision:
    input_mappings:
      # Forward/backward movement
      - id: "forward_movement"
        source_type: axis
        source_index: 1          # Left stick Y
        scale: 0.5               # Normal speed
        deadzone: 0.1
        action:
          type: publish
          topic: "/cmd_vel"
          message_type: "geometry_msgs/msg/Twist"
          field: "linear.x"
      
      # Rotation
      - id: "rotation"
        source_type: axis
        source_index: 3          # Right stick X
        scale: 0.8               # Normal rotation speed
        deadzone: 0.1
        action:
          type: publish
          topic: "/cmd_vel"
          message_type: "geometry_msgs/msg/Twist"
          field: "angular.z"
      
      # R1 button - Turbo mode (doubles speed)
      - source_type: button
        source_index: 5
        action:
          type: modifier
          targets:
            - mapping_id: "forward_movement"
            - mapping_id: "rotation"
          scale_multiplier: 2.0
      
      # L1 button - Precision mode (reduces speed to 30%)
      - source_type: button
        source_index: 4
        action:
          type: modifier
          targets:
            - mapping_id: "forward_movement"
            - mapping_id: "rotation"
          scale_multiplier: 0.3
          deadzone_override: 0.05  # Also reduce deadzone for fine control
      
      # Right trigger - Variable speed boost
      - source_type: axis
        source_index: 5          # Right trigger
        deadzone: 0.1
        action:
          type: modifier
          targets:
            # Target by source instead of ID
            - source:
                type: axis
                index: 1         # Left stick Y
          scale_multiplier: 3.0  # Up to 3x boost at full trigger
          apply_gradually: true  # Scale based on trigger position

  # Profile demonstrating safety features
  safety_mode:
    enable_button: 7             # Must hold button 7 to move
    
    input_mappings:
      # Movement (requires enable button)
      - source_type: axis
        source_index: 1
        scale: 0.3               # Slow default speed
        deadzone: 0.15
        action:
          type: publish
          topic: "/cmd_vel"
          message_type: "geometry_msgs/msg/Twist"
          field: "linear.x"
      
      # Emergency stop button (works without enable button)
      - source_type: button
        source_index: 0          # X button
        action:
          type: modifier
          targets:
            - source:
                type: axis
                index: 1
          scale_multiplier: 0.0  # Zero out all movement
      
      # Speed limiter based on sensor input (simulated with axis)
      - source_type: axis
        source_index: 6          # Could be proximity sensor value
        scale: -1.0              # Invert so closer = slower
        offset: 1.0              # Transform to 0-1 range
        action:
          type: modifier
          targets:
            - source:
                type: axis
                index: 1
          apply_gradually: true
          scale_multiplier: 1.0  # Actual multiplier comes from axis value

  # Complex modifier stacking example
  modifier_stacking:
    input_mappings:
      # Base movement
      - id: "move"
        source_type: axis
        source_index: 1
        scale: 1.0
        action:
          type: publish
          topic: "/cmd_vel"
          message_type: "geometry_msgs/msg/Twist"
          field: "linear.x"
      
      # Multiple modifiers can stack
      # Final scale = base * mod1 * mod2 * ...
      
      # Modifier 1: 2x multiplier
      - source_type: button
        source_index: 4
        action:
          type: modifier
          targets:
            - mapping_id: "move"
          scale_multiplier: 2.0
      
      # Modifier 2: 0.5x multiplier
      - source_type: button
        source_index: 5
        action:
          type: modifier
          targets:
            - mapping_id: "move"
          scale_multiplier: 0.5
      
      # With both pressed: 1.0 * 2.0 * 0.5 = 1.0 (back to normal)
      
      # Offset modifier example
      - source_type: button
        source_index: 6
        action:
          type: modifier
          targets:
            - mapping_id: "move"
          offset_delta: 0.2      # Add constant forward bias