# PlayStation 4 Controller Configuration
# Button and axis mappings for PS4 DualShock controller

# Controller mapping reference:
# Axes:
#   0: Left stick X (left: -1.0, right: 1.0)
#   1: Left stick Y (up: -1.0, down: 1.0)
#   2: Right stick X (left: -1.0, right: 1.0)
#   3: L2 trigger (released: 1.0, pressed: -1.0)
#   4: Right stick Y (up: -1.0, down: 1.0)
#   5: R2 trigger (released: 1.0, pressed: -1.0)
#
# Buttons:
#   0: Square
#   1: X (Cross)
#   2: Circle
#   3: Triangle
#   4: L1
#   5: R1
#   6: L2 (digital)
#   7: R2 (digital)
#   8: Share
#   9: Options
#   10: L3 (left stick press)
#   11: R3 (right stick press)
#   12: PS button
#   13: Touchpad press

default_profile: "ps4_teleop"

profiles:
  ps4_teleop:
    # L1 button for safety
    enable_button: 4
    
    input_mappings:
      # Forward/backward with left stick
      - source_type: axis
        source_index: 1
        scale: -0.5       # Inverted because PS4 Y-axis is inverted
        offset: 0.0
        deadzone: 0.1
        action:
          type: publish_twist_field
          field: linear_x
      
      # Rotation with right stick
      - source_type: axis
        source_index: 2
        scale: -1.0       # Adjust sign based on preference
        offset: 0.0
        deadzone: 0.1
        action:
          type: publish_twist_field
          field: angular_z
    
      # Square button - full stop
      - source_type: button
        source_index: 0
        scale: 0.0        # Zero for full stop
        offset: 0.0
        deadzone: 0.0
        action:
          type: publish_twist_field
          field: linear_x

  ps4_triggers:
    # Use triggers for forward/backward control
    # No enable button (-1 means always enabled)
    
    input_mappings:
      # R2 for forward (scale negative values to positive forward motion)
      - source_type: axis
        source_index: 5
        scale: -0.5
        offset: 0.25      # Offset to handle trigger rest position
        deadzone: 0.2
        action:
          type: publish_twist_field
          field: linear_x
      
      # L2 for backward (scale to negative motion)
      - source_type: axis
        source_index: 3
        scale: 0.5
        offset: -0.25
        deadzone: 0.2
        action:
          type: publish_twist_field
          field: linear_x
      
      # Right stick for steering
      - source_type: axis
        source_index: 2
        scale: -1.0
        offset: 0.0
        deadzone: 0.1
        action:
          type: publish_twist_field
          field: angular_z