# Example configuration demonstrating service call mappings
# This shows how to map joystick buttons to ROS2 service calls

default_profile: "service_calls_example"

profiles:
  service_calls_example:
    input_mappings:
      # Button 0 (X button on PS4) - Reset odometry
      - source_type: button
        source_index: 0
        scale: 1.0
        offset: 0.0
        deadzone: 0.0
        action:
          type: call_service
          service_name: "/reset_odometry"
          service_type: "std_srvs/srv/Trigger"
      
      # Button 1 (Circle button on PS4) - Clear costmap
      - source_type: button
        source_index: 1
        scale: 1.0
        offset: 0.0
        deadzone: 0.0
        action:
          type: call_service
          service_name: "/clear_costmap"
          service_type: "std_srvs/srv/Empty"
      
      # Button 2 (Triangle button on PS4) - Start recording
      - source_type: button
        source_index: 2
        scale: 1.0
        offset: 0.0
        deadzone: 0.0
        action:
          type: call_service
          service_name: "/start_recording"
          service_type: "std_srvs/srv/Trigger"
      
      # Button 3 (Square button on PS4) - Stop recording
      - source_type: button
        source_index: 3
        scale: 1.0
        offset: 0.0
        deadzone: 0.0
        action:
          type: call_service
          service_name: "/stop_recording"
          service_type: "std_srvs/srv/Trigger"
      
      # Button 4 (L1) - Emergency stop
      - source_type: button
        source_index: 4
        scale: 1.0
        offset: 0.0
        deadzone: 0.0
        action:
          type: call_service
          service_name: "/emergency_stop"
          service_type: "std_srvs/srv/Trigger"
      
      # Button 5 (R1) - Resume operation
      - source_type: button
        source_index: 5
        scale: 1.0
        offset: 0.0
        deadzone: 0.0
        action:
          type: call_service
          service_name: "/resume_operation"
          service_type: "std_srvs/srv/Empty"