# Xbox Controller Configuration
# Button and axis mappings for Xbox One/Series controllers

# Controller mapping reference:
# Axes:
#   0: Left stick X (left: -1.0, right: 1.0)
#   1: Left stick Y (up: -1.0, down: 1.0)
#   2: LT trigger (released: 1.0, pressed: -1.0)
#   3: Right stick X (left: -1.0, right: 1.0)
#   4: Right stick Y (up: -1.0, down: 1.0)
#   5: RT trigger (released: 1.0, pressed: -1.0)
#   6: D-pad X (left: -1.0, right: 1.0)
#   7: D-pad Y (up: -1.0, down: 1.0)
#
# Buttons:
#   0: A
#   1: B
#   2: X
#   3: Y
#   4: LB (left bumper)
#   5: RB (right bumper)
#   6: Back/View
#   7: Start/Menu
#   8: Xbox button
#   9: Left stick press
#   10: Right stick press

default_profile: "xbox_teleop"

profiles:
  xbox_teleop:
    # LB button for safety
    enable_button: 4
    
    input_mappings:
      # Forward/backward with left stick
      - source_type: axis
        source_index: 1
        scale: -0.5       # Inverted because Xbox Y-axis is inverted
        offset: 0.0
        deadzone: 0.1
        action:
          type: publish_twist_field
          field: linear_x
      
      # Rotation with right stick
      - source_type: axis
        source_index: 3
        scale: 1.0
        offset: 0.0
        deadzone: 0.1
        action:
          type: publish_twist_field
          field: angular_z
    
      # A button - slow forward
      - source_type: button
        source_index: 0
        scale: 0.2        # Fixed forward speed
        offset: 0.0
        deadzone: 0.0
        action:
          type: publish_twist_field
          field: linear_x
      
      # B button - stop
      - source_type: button
        source_index: 1
        scale: 0.0        # Zero for full stop
        offset: 0.0
        deadzone: 0.0
        action:
          type: publish_twist_field
          field: linear_x

  xbox_racing:
    # Racing-style controls with triggers
    # No enable button
    
    input_mappings:
      # RT for forward acceleration
      - source_type: axis
        source_index: 5
        scale: -1.0       # Scale trigger input to forward speed
        offset: 0.5       # Offset to make trigger center = 0 speed
        deadzone: 0.1
        action:
          type: publish_twist_field
          field: linear_x
      
      # LT for reverse/brake
      - source_type: axis
        source_index: 2
        scale: 0.5        # Slower reverse speed
        offset: -0.25
        deadzone: 0.1
        action:
          type: publish_twist_field
          field: linear_x
      
      # Left stick for steering
      - source_type: axis
        source_index: 0
        scale: 1.5        # More responsive steering
        offset: 0.0
        deadzone: 0.05
        action:
          type: publish_twist_field
          field: angular_z

  xbox_dpad:
    # D-pad only control for precise movement
    
    input_mappings:
      # D-pad Y for forward/backward
      - source_type: axis
        source_index: 7
        scale: -0.3       # Fixed speed, no analog control
        offset: 0.0
        deadzone: 0.5     # High deadzone for digital behavior
        action:
          type: publish_twist_field
          field: linear_x
      
      # D-pad X for rotation
      - source_type: axis
        source_index: 6
        scale: 0.5
        offset: 0.0
        deadzone: 0.5
        action:
          type: publish_twist_field
          field: angular_z