name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:humble-desktop
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y curl build-essential git
    
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install cargo-llvm-cov
      run: |
        $HOME/.cargo/bin/cargo install cargo-llvm-cov
    
    - name: Generate coverage
      run: |
        source /opt/ros/humble/setup.bash
        $HOME/.cargo/bin/cargo llvm-cov --all-features --lcov --output-path lcov.info
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: lcov.info
        fail_ci_if_error: true
        verbose: true