name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup ROS 2 Humble
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview
        
    - name: Install dependencies
      run: |
        cargo install cargo-llvm-cov
        cargo install safe_drive_msg
        
    - name: Generate messages
      run: |
        source /opt/ros/humble/setup.bash
        mkdir -p /tmp/safe_drive_msgs
        safe_drive_msg std_msgs -o /tmp/safe_drive_msgs -p
        safe_drive_msg sensor_msgs -o /tmp/safe_drive_msgs -p
        safe_drive_msg geometry_msgs -o /tmp/safe_drive_msgs -p
        
    - name: Generate coverage
      run: |
        source /opt/ros/humble/setup.bash
        cargo llvm-cov --all-features --lcov --output-path lcov.info
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: lcov.info
        fail_ci_if_error: true
        verbose: true