name: Release

on:
  release:
    types: [published]

jobs:
  # Build debian packages for different ROS2 distributions
  build-deb:
    name: Build Debian Package (${{ matrix.ros_distro }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ros_distro: [humble]  # Add iron later when tested
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup ROS 2 ${{ matrix.ros_distro }}
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: ${{ matrix.ros_distro }}
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-colcon-common-extensions \
          python3-bloom \
          python3-rosdep \
          fakeroot \
          dpkg-dev \
          debhelper
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install cargo-ament-build
      run: cargo install cargo-ament-build
    
    - name: Get version
      id: get_version
      run: |
        VERSION=${{ github.event.release.tag_name }}
        VERSION=${VERSION#v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "DEB_VERSION=${VERSION}-0${MATRIX_ROS_DISTRO}0" >> $GITHUB_OUTPUT
      env:
        MATRIX_ROS_DISTRO: ${{ matrix.ros_distro }}
    
    - name: Build debian package
      run: |
        # Create workspace
        mkdir -p ws/src
        ln -s $GITHUB_WORKSPACE ws/src/joy_msg_router_rs
        cd ws
        
        # Build
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        colcon build --packages-select joy_msg_router_rs
        
        # Create debian structure
        cd $GITHUB_WORKSPACE
        mkdir -p debian/DEBIAN
        mkdir -p debian/opt/ros/${{ matrix.ros_distro }}
        
        # Copy built files
        cp -r ws/install/joy_msg_router_rs/* debian/opt/ros/${{ matrix.ros_distro }}/
        
        # Create control file
        cat > debian/DEBIAN/control << EOF
        Package: ros-${{ matrix.ros_distro }}-joy-msg-router-rs
        Version: ${{ steps.get_version.outputs.DEB_VERSION }}
        Section: misc
        Priority: optional
        Architecture: amd64
        Depends: ros-${{ matrix.ros_distro }}-ros-base, ros-${{ matrix.ros_distro }}-joy
        Maintainer: ROS2 Joy Router <noreply@anthropic.com>
        Description: ROS2 Joy Message Router
         A ROS2 node written in Rust that routes joystick messages to robot control commands.
        EOF
        
        # Build package
        dpkg-deb --build debian
        mv debian.deb ros-${{ matrix.ros_distro }}-joy-msg-router-rs_${{ steps.get_version.outputs.DEB_VERSION }}_amd64.deb
    
    - name: Upload debian package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./ros-${{ matrix.ros_distro }}-joy-msg-router-rs_${{ steps.get_version.outputs.DEB_VERSION }}_amd64.deb
        asset_name: ros-${{ matrix.ros_distro }}-joy-msg-router-rs_${{ steps.get_version.outputs.DEB_VERSION }}_amd64.deb
        asset_content_type: application/vnd.debian.binary-package

  # Create release notes
  update-release-notes:
    name: Update Release Notes
    runs-on: ubuntu-latest
    needs: [build-deb]
    permissions:
      contents: write
    steps:
    - name: Update release
      uses: tubone24/update_release@v1.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: |
          ## Installation
          
          ### Debian/Ubuntu with ROS2
          
          Download the appropriate .deb file for your ROS2 distribution and install:
          ```bash
          sudo dpkg -i ros-<distro>-joy-msg-router-rs_*.deb
          sudo apt-get install -f  # Install any missing dependencies
          ```
          
          ### From Source
          
          ```bash
          cd ~/ros2_ws/src
          git clone <repository-url> joy_msg_router_rs
          cd ~/ros2_ws
          colcon build --packages-select joy_msg_router_rs
          ```
          
          ## What's Changed
          
          See the full changelog for details.
        is_append_body: true