name: ROS2 Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-ros2:
    name: ROS2 Tests - ${{ matrix.ros_distro }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ros_distro: [humble]  # Iron support can be added later
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup ROS 2 ${{ matrix.ros_distro }}
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: ${{ matrix.ros_distro }}
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-colcon-common-extensions \
          python3-pip \
          python3-pytest \
          python3-pytest-cov \
          ros-${{ matrix.ros_distro }}-joy
        
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
        
    - name: Install cargo-ament-build
      run: cargo install cargo-ament-build
    
    - name: Create workspace
      run: |
        mkdir -p ~/ws/src
        ln -s $GITHUB_WORKSPACE ~/ws/src/
    
    - name: Build package
      run: |
        cd ~/ws
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        colcon build --packages-select joy_msg_router_rs
    
    - name: Run tests
      run: |
        cd ~/ws
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        source install/setup.bash
        colcon test --packages-select joy_msg_router_rs --pytest-args -v
        colcon test-result --verbose
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.ros_distro }}
        path: ~/ws/build/joy_msg_router_rs/test_results