name: ROS2 Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-ros2:
    name: ROS2 Tests - ${{ matrix.ros_distro }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ros_distro: [humble]  # Iron support can be added later
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup ROS 2 ${{ matrix.ros_distro }}
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: ${{ matrix.ros_distro }}
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-colcon-common-extensions \
          python3-pip \
          python3-pytest \
          python3-pytest-cov \
          ros-${{ matrix.ros_distro }}-joy
        
        # Install colcon plugins for cargo
        pip3 install colcon-cargo colcon-ros-cargo
        
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
        
    - name: Install cargo-ament-build from Tier4
      run: |
        # Install to system cargo location to avoid conflicts
        sudo mkdir -p /usr/local/cargo/bin
        git clone https://github.com/tier4/cargo-ament-build.git
        cd cargo-ament-build
        cargo build --release
        sudo cp target/release/cargo-ament-build /usr/local/cargo/bin/
        # Make it available in PATH
        echo "/usr/local/cargo/bin" >> $GITHUB_PATH
    
    - name: Create workspace
      run: |
        mkdir -p ~/ws/src
        ln -s $GITHUB_WORKSPACE ~/ws/src/
    
    - name: Build package
      run: |
        cd ~/ws
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        export PATH="/usr/local/cargo/bin:$PATH"
        colcon build --packages-select joy_msg_router_rs
    
    - name: Run tests
      run: |
        cd ~/ws
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        source install/setup.bash
        colcon test --packages-select joy_msg_router_rs --pytest-args -v
        colcon test-result --verbose
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.ros_distro }}
        path: ~/ws/build/joy_msg_router_rs/test_results